/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.form;

import domain.Delegat;
import domain.Panel;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import uicontroller.Controller;

/**
 *
 * @author Milan
 */
public class FrmIzmeniDelegat extends javax.swing.JFrame {

    /**
     * Creates new form FrmIzmeniDelegat
     */
    private FrmDelegat frmDelegat;
    private Delegat izabraniDelegat;

    public FrmIzmeniDelegat(FrmDelegat frmDelegat) {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);

        this.frmDelegat = frmDelegat;
        izabraniDelegat = frmDelegat.getIzabraniDelegat();
        popuniCmb();
        popuniFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        txtPrezime = new javax.swing.JTextField();
        txtJmbg = new javax.swing.JTextField();
        cmbPaneli = new javax.swing.JComboBox();
        btnChange = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ime");

        jLabel2.setText("prezime");

        jLabel3.setText("jmbg");

        jLabel4.setText("panel");

        btnChange.setText("izmeni");
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });

        btnCancel.setText("izadji");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPrezime)
                                    .addComponent(txtJmbg)
                                    .addComponent(cmbPaneli, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnChange)
                        .addGap(38, 38, 38)
                        .addComponent(btnCancel)))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtJmbg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbPaneli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChange)
                    .addComponent(btnCancel))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        String ime = txtIme.getText();
        String prezime = txtPrezime.getText();
        String jmbg = txtJmbg.getText();
        int indeks = cmbPaneli.getSelectedIndex();
        if (validirajFormu(ime, prezime, jmbg, indeks)) {
            try {
                izabraniDelegat.setIme(txtIme.getText());
                izabraniDelegat.setPrezime(txtPrezime.getText());
                izabraniDelegat.setJmbg(Long.valueOf(txtJmbg.getText()));
                izabraniDelegat.setPanelid((Panel) cmbPaneli.getSelectedItem());
                Controller.getInstance().preomeniDelegat(izabraniDelegat);
                JOptionPane.showMessageDialog(this, "Delegat changed!\nGenerated ID: [" + izabraniDelegat.getId() + "]", "Change Delegat", JOptionPane.INFORMATION_MESSAGE);
                frmDelegat.popuniTabelu();
                dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Delegat not changed!\n" + ex.getMessage(), "Change Delegat", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnChangeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnChange;
    private javax.swing.JComboBox cmbPaneli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtJmbg;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables
private void popuniCmb() {
        try {
            List<Panel> paneli = Controller.getInstance().vratiPanele();

            for (Panel panel : paneli) {
                cmbPaneli.addItem(panel);
            }
        } catch (Exception ex) {
            Logger.getLogger(FrmNewDelegat.class.getName()).log(Level.SEVERE, null, ex);
        }
        cmbPaneli.setSelectedIndex(-1);
    }

    private void popuniFormu() {
        txtIme.setText(izabraniDelegat.getIme());
        txtPrezime.setText(izabraniDelegat.getPrezime());
        txtJmbg.setText(String.valueOf(izabraniDelegat.getJmbg()));
        if (izabraniDelegat.getPanelid().getId() != 0) {
            cmbPaneli.setSelectedIndex(izabraniDelegat.getPanelid().getId() - 1);
        }
        //cmbPaneli.setSelectedItem(izabraniDelegat.getPanelid());
//        System.out.println(izabraniDelegat.getPanelid());

    }

    private boolean validirajFormu(String ime, String prezime, String jmbg, int indeks) {
        boolean signal = true;
        if (ime.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Polje ime je prazno");
            signal = false;
        }
        if (prezime.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Polje prezime je prazno");
            signal = false;
        }
        if (jmbg.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Polje jmbg je prazno");
            signal = false;
        }

        if (indeks == -1) {
            JOptionPane.showMessageDialog(this, "Niste izabrali panel");
            signal = false;
        }

        if (!ime.isEmpty()) {
            if (ime.length() > 20) {
                JOptionPane.showMessageDialog(this, "Ime moze da sadrzi najvise 20 karkatera");
                signal = false;
            }
        }

        if (!ime.isEmpty()) {
            if (ime.length() < 4) {
                JOptionPane.showMessageDialog(this, "Ime mora da sadrzi najmanje 4 karaktera");
                signal = false;
            }
        }

        if (!prezime.isEmpty()) {
            if (prezime.length() > 20) {
                JOptionPane.showMessageDialog(this, "Prezime moze da sadrzi najvise 20 karkatera");
                signal = false;
            }
        }

        if (!prezime.isEmpty()) {
            if (prezime.length() < 4) {
                JOptionPane.showMessageDialog(this, "Prezime mora da sadrzi najmanje 4 karaktera");
                signal = false;
            }
        }

        if (!jmbg.isEmpty()) {
            if (jmbg.length() != 13) {
                JOptionPane.showMessageDialog(this, "Jmbg mora da sadrzi tacno 13 karkatera");
                signal = false;
            }
        }
        if (!jmbg.isEmpty()) {
            if (jmbg.length() == 13) {
                if (!jmbg.matches("\\d+")) {
                    JOptionPane.showMessageDialog(this, "Jmbg mora da sadrzi samo cifre");
                    signal = false;
                }
            }
        }

        if (!ime.isEmpty()) {
            if (ime.length() >= 4 && ime.length() <= 20) {
                if (!ime.matches("[a-zA-Z]+")) {
                    JOptionPane.showMessageDialog(this, "Ime mora da sadrzi samo slova");
                    signal = false;
                }
            }
        }

        if (!prezime.isEmpty()) {
            if (prezime.length() >= 4 && prezime.length() <= 20) {
                if (!prezime.matches("[a-zA-Z]+")) {
                    JOptionPane.showMessageDialog(this, "Prezime mora da sadrzi samo slova");
                    signal = false;
                }
            }
        }

        return signal;
    }

}
