/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.form;

import domain.Panel;
import domain.Rezervacija;
import domain.Sala;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Properties;
import javax.swing.JOptionPane;
import org.jdatepicker.impl.JDatePanelImpl;
import org.jdatepicker.impl.JDatePickerImpl;
import org.jdatepicker.impl.UtilDateModel;
import table.model.TableModelRezervacija;
import ui.form.dateformatter.DateLabelFormatter;
import uicontroller.Controller;

/**
 *
 * @author Milan
 */
public class FrmIzmeniRezervaciju extends javax.swing.JFrame {

    /**
     * Creates new form FrmIzmeniRezervaciju
     */
    JDatePickerImpl datePicker;
    UtilDateModel model;
    LocalDate localDate;
    List<Rezervacija> rezervacije=new ArrayList<>();
    List<Rezervacija> rezervacijeZaPromenu=new ArrayList<>();
    private Rezervacija izabranaRezervacija;
    public FrmIzmeniRezervaciju() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        popuniCmbPaneli();
        popuniCmbSale();
        inicijalizujKalendar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReserveAll = new javax.swing.JButton();
        btnReserve = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        cmbSale = new javax.swing.JComboBox<>();
        btnCancel = new javax.swing.JButton();
        cmbVreme = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSveRezervacije = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        panelDate = new javax.swing.JPanel();
        cmbPaneli = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblRezervacijePromena = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnReserveAll.setBackground(new java.awt.Color(51, 255, 0));
        btnReserveAll.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReserveAll.setForeground(new java.awt.Color(64, 43, 58));
        btnReserveAll.setText("rezervisi sve");
        btnReserveAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReserveAllActionPerformed(evt);
            }
        });

        btnReserve.setBackground(new java.awt.Color(102, 255, 0));
        btnReserve.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReserve.setForeground(new java.awt.Color(64, 43, 58));
        btnReserve.setText("rezervisi");
        btnReserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReserveActionPerformed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(102, 255, 0));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(64, 43, 58));
        btnSearch.setText("pretrazi");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(0, 204, 0));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(64, 43, 58));
        btnCancel.setText("izadji");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        cmbVreme.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10:00", "12:00", "14:00", "16:00", "18:00", "20:00" }));
        cmbVreme.setSelectedIndex(-1);

        jLabel3.setText("Panel");

        tblSveRezervacije.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSveRezervacije.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSveRezervacijeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblSveRezervacije);

        jLabel5.setText("Vreme");

        panelDate.setAlignmentX(70.0F);
        panelDate.setAlignmentY(10.0F);
        panelDate.setPreferredSize(new java.awt.Dimension(200, 30));

        javax.swing.GroupLayout panelDateLayout = new javax.swing.GroupLayout(panelDate);
        panelDate.setLayout(panelDateLayout);
        panelDateLayout.setHorizontalGroup(
            panelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 257, Short.MAX_VALUE)
        );
        panelDateLayout.setVerticalGroup(
            panelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 101, Short.MAX_VALUE)
        );

        jLabel1.setText("Datum");

        jLabel2.setText("Sala");

        tblRezervacijePromena.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblRezervacijePromena);

        jSeparator1.setBackground(new java.awt.Color(51, 255, 51));
        jSeparator1.setForeground(new java.awt.Color(51, 255, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(panelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnSearch)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnReserve)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel5))
                                                .addGap(41, 41, 41))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbVreme, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(cmbSale, 0, 197, Short.MAX_VALUE)
                                                .addComponent(cmbPaneli, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGap(28, 28, 28)))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane4)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReserveAll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSearch))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cmbPaneli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbSale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbVreme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReserve)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReserveAll)
                    .addComponent(btnCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReserveAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReserveAllActionPerformed
        try {

            System.out.println(rezervacijeZaPromenu);
            Controller.getInstance().promeniRezervacije(rezervacijeZaPromenu);
            JOptionPane.showMessageDialog(this, "Uspesno izmenjene rezervacije", "Izmena", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception ex) {
            //Logger.getLogger(FrmIzmeniRezervaciju.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Neuspesno izmenjene rezervacije", "Izmena", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_btnReserveAllActionPerformed

    private void btnReserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReserveActionPerformed
        
        Date izabraniDatum=(Date)model.getValue();
        localDate=dateToLocalDate(izabraniDatum);
        izabranaRezervacija.setDatum(localDate);
        izabranaRezervacija.setPanelid((Panel) cmbPaneli.getSelectedItem());
        izabranaRezervacija.setSalaid((Sala) cmbSale.getSelectedItem());
        izabranaRezervacija.setVremeOd(LocalTime.parse((CharSequence) cmbVreme.getSelectedItem()));
        LocalTime vremeOd=izabranaRezervacija.getVremeOd();
        LocalTime vremeDo=vremeOd.plusHours(2);
        rezervacijeZaPromenu.add(izabranaRezervacija);
        popuniTabeluPromenjenihRezervacija(rezervacijeZaPromenu);
    }//GEN-LAST:event_btnReserveActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

        Date izabraniDatum=(Date)model.getValue();
        localDate=dateToLocalDate(izabraniDatum);
        System.out.println("Izabrani datum: " + localDate);

        Rezervacija rezervacija = new Rezervacija();
        rezervacija.setDatum(localDate);
        
        try {
            rezervacije = Controller.getInstance().nadjiRezervacijuPoDatumu(rezervacija);
            popuniTabelu();
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(FrmKreirajRezervaciju.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void tblSveRezervacijeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSveRezervacijeMouseClicked

        int red=tblSveRezervacije.getSelectedRow();
        izabranaRezervacija=rezervacije.get(red);
        System.out.println(izabranaRezervacija.getVremeOd());
        cmbPaneli.setSelectedItem(izabranaRezervacija.getPanelid());
        cmbSale.setSelectedItem(izabranaRezervacija.getSalaid());
        cmbVreme.setSelectedItem(String.valueOf(izabranaRezervacija.getVremeOd()));
    }//GEN-LAST:event_tblSveRezervacijeMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnReserve;
    private javax.swing.JButton btnReserveAll;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox cmbPaneli;
    private javax.swing.JComboBox<Object> cmbSale;
    private javax.swing.JComboBox cmbVreme;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelDate;
    private javax.swing.JTable tblRezervacijePromena;
    private javax.swing.JTable tblSveRezervacije;
    // End of variables declaration//GEN-END:variables

    private void popuniCmbPaneli() {
        try {
            List<Panel> paneli = Controller.getInstance().vratiPanele();

            for (Panel panel : paneli) {
                cmbPaneli.addItem(panel);
            }
            cmbPaneli.setSelectedIndex(-1);
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(FrmNewDelegat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    private void popuniCmbSale() {
        try {
            List<Sala> sale = Controller.getInstance().vratiSale();

            for (Sala s : sale) {
                cmbSale.addItem(s);
            }
            cmbSale.setSelectedIndex(-1);
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(FrmNewDelegat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    private void inicijalizujKalendar() {
        model = new UtilDateModel();
        Properties p = new Properties();
        JDatePanelImpl datePanel = new JDatePanelImpl(model, p);

        // Kreiranje JDatePicker
        datePicker = new JDatePickerImpl(datePanel, new DateLabelFormatter());

        
        panelDate.setLayout(null); 

        panelDate.setBounds(35, 10, 200, 30);
        datePicker.setBounds(35, 10, 200, 30);

        panelDate.add(datePicker);
    }
    
    private LocalDate dateToLocalDate(Date odabraniDatum) {
        return Instant.ofEpochMilli(odabraniDatum.getTime()).atZone(ZoneId.systemDefault()).toLocalDate();
    }

    private void popuniTabelu() {
        try {
            TableModelRezervacija modelRez = new TableModelRezervacija(rezervacije);
            tblSveRezervacije.setModel(modelRez);
        } catch (Exception e) {
            System.out.println("Tabela nije uspesno popunjena");
            e.printStackTrace();
        }
    }

    private void popuniTabeluPromenjenihRezervacija(List<Rezervacija> rezervacijeZaPromenu) {
        try {
            TableModelRezervacija modelrez = new TableModelRezervacija(rezervacijeZaPromenu);
            tblRezervacijePromena.setModel(modelrez);
        } catch (Exception ex) {
            System.out.println("Tabela nije uspesno popunjena");
            ex.printStackTrace();
        }
    }

    
}
