/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.form;

import domain.Panel;
import domain.Rezervacija;
import domain.Sala;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jdatepicker.impl.JDatePanelImpl;
import org.jdatepicker.impl.JDatePickerImpl;
import org.jdatepicker.impl.UtilDateModel;
import table.model.TableModelRezervacija;
import ui.form.dateformatter.DateLabelFormatter;
import uicontroller.Controller;

public class FrmKreirajRezervaciju extends javax.swing.JFrame {

    JDatePickerImpl datePicker;
    UtilDateModel model;
    LocalDate localDate;
    List<Rezervacija> rezervacije = new ArrayList<>();
    List<Rezervacija> rezervacijeZaUbacivanje = new ArrayList<>();

    public FrmKreirajRezervaciju() {
        initComponents();

        setLocationRelativeTo(null);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);

        popuniCmbPaneli();
        popuniCmbSale();
        inicijalizujKalendar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReserve = new javax.swing.JButton();
        cmbVreme = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSveRezervacije = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblKreiranjeRezervacije = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        btnReserveAll = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelDate = new javax.swing.JPanel();
        cmbPaneli = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        cmbSale = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnReserve.setBackground(new java.awt.Color(51, 255, 51));
        btnReserve.setForeground(new java.awt.Color(64, 43, 58));
        btnReserve.setText("rezervisi");
        btnReserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReserveActionPerformed(evt);
            }
        });

        cmbVreme.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08:00:00", "10:00:00", "12:00:00", "14:00:00", "16:00:00", "18:00:00", "20:00:00" }));
        cmbVreme.setSelectedIndex(-1);

        tblSveRezervacije.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblSveRezervacije);

        tblKreiranjeRezervacije.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblKreiranjeRezervacije);

        jSeparator1.setBackground(new java.awt.Color(0, 204, 0));
        jSeparator1.setForeground(new java.awt.Color(51, 204, 0));

        btnReserveAll.setBackground(new java.awt.Color(51, 255, 51));
        btnReserveAll.setForeground(new java.awt.Color(64, 43, 58));
        btnReserveAll.setText("rezervisi sve");
        btnReserveAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReserveAllActionPerformed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(51, 255, 51));
        btnSearch.setForeground(new java.awt.Color(64, 43, 58));
        btnSearch.setText("pretrazi");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(153, 255, 153));
        btnCancel.setForeground(new java.awt.Color(64, 43, 58));
        btnCancel.setText("izadji");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel3.setText("Panel");

        jLabel4.setText("Sala");

        jLabel5.setText("Vreme");

        panelDate.setAlignmentX(70.0F);
        panelDate.setAlignmentY(10.0F);
        panelDate.setPreferredSize(new java.awt.Dimension(200, 30));

        javax.swing.GroupLayout panelDateLayout = new javax.swing.GroupLayout(panelDate);
        panelDate.setLayout(panelDateLayout);
        panelDateLayout.setHorizontalGroup(
            panelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 257, Short.MAX_VALUE)
        );
        panelDateLayout.setVerticalGroup(
            panelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 101, Short.MAX_VALUE)
        );

        jLabel1.setText("Datum");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(panelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 23, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnSearch)))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnReserve)
                                        .addGap(133, 133, 133))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5))
                                        .addGap(22, 22, 22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbVreme, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbPaneli, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbSale, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReserveAll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel1)))
                        .addGap(58, 58, 58)
                        .addComponent(btnSearch))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cmbPaneli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cmbSale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbVreme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addComponent(btnReserve))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReserveAll)
                    .addComponent(btnCancel))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReserveActionPerformed

        Rezervacija r = new Rezervacija();
        r.setPanelid((Panel) cmbPaneli.getSelectedItem());
        r.setSalaid((Sala) cmbSale.getSelectedItem());
        r.setDatum(localDate);
        r.setVremeOd(LocalTime.parse((CharSequence) cmbVreme.getSelectedItem()));
        LocalTime vremeOd=r.getVremeOd();
        LocalTime vremeDo=vremeOd.plusHours(2);
        r.setVremeDo(vremeDo);
        rezervacijeZaUbacivanje.add(r);

        popuniTabelu2(rezervacijeZaUbacivanje);
    }//GEN-LAST:event_btnReserveActionPerformed

    private void btnReserveAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReserveAllActionPerformed
        try {

            Controller.getInstance().dodajRezervacije(rezervacijeZaUbacivanje);
            JOptionPane.showMessageDialog(this, "Uspesno unete rezervacije", "Uspesno", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception ex) {
            Logger.getLogger(FrmKreirajRezervaciju.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnReserveAllActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

        Date izabraniDatum = (Date) model.getValue();
        localDate = dateToLocalDate(izabraniDatum);
        System.out.println("Izabrani datum: " + localDate);

        Rezervacija rezervacija = new Rezervacija();
        rezervacija.setDatum(localDate);

        try {
            rezervacije = Controller.getInstance().nadjiRezervacijuPoDatumu(rezervacija);
            popuniTabelu();
        } catch (Exception ex) {
            Logger.getLogger(FrmKreirajRezervaciju.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnReserve;
    private javax.swing.JButton btnReserveAll;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox cmbPaneli;
    private javax.swing.JComboBox cmbSale;
    private javax.swing.JComboBox<String> cmbVreme;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelDate;
    private javax.swing.JTable tblKreiranjeRezervacije;
    private javax.swing.JTable tblSveRezervacije;
    // End of variables declaration//GEN-END:variables

    private void popuniCmbPaneli() {
        try {
            List<Panel> paneli = Controller.getInstance().vratiPanele();

            for (Panel panel : paneli) {
                cmbPaneli.addItem(panel);
            }
            cmbPaneli.setSelectedIndex(-1);
        } catch (Exception ex) {
            Logger.getLogger(FrmNewDelegat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private LocalDate dateToLocalDate(Date odabraniDatum) {
        return Instant.ofEpochMilli(odabraniDatum.getTime()).atZone(ZoneId.systemDefault()).toLocalDate();
    }

    private void popuniTabelu() {
        try {
            TableModelRezervacija modelRez = new TableModelRezervacija(rezervacije);
            tblSveRezervacije.setModel(modelRez);
        } catch (Exception e) {
            System.out.println("Tabela nije uspesno popunjena");
            e.printStackTrace();
        }
    }

    private void popuniTabelu2(List<Rezervacija> rezervacije) {
        try {
            TableModelRezervacija modelRez = new TableModelRezervacija(rezervacije);
            tblKreiranjeRezervacije.setModel(modelRez);
        } catch (Exception e) {
            System.out.println("Tabela nije uspesno popunjena");
            e.printStackTrace();
        }
    }

    private void inicijalizujKalendar() {
        
        model = new UtilDateModel();
        Properties p = new Properties();
        JDatePanelImpl datePanel = new JDatePanelImpl(model, p);

        
        datePicker = new JDatePickerImpl(datePanel, new DateLabelFormatter());

        
        panelDate.setLayout(null); 

        
        panelDate.setBounds(35, 10, 200, 30);
        datePicker.setBounds(35, 10, 200, 30); 

        
        panelDate.add(datePicker);
    }

    private void popuniCmbSale() {
        try {
            List<Sala> sale = Controller.getInstance().vratiSale();

            for (Sala s : sale) {
                cmbSale.addItem(s);
            }
            cmbSale.setSelectedIndex(-1);
        } catch (Exception ex) {
            Logger.getLogger(FrmNewDelegat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
