/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.form;

import domain.Admin;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import uicontroller.Controller;


public class FrmMain extends javax.swing.JFrame {

    private Admin admin;

    /**
     * Creates new form FrmMain
     */
    public FrmMain(Admin admin) {
        this.admin = admin;
        initComponents();
        setTitle(admin.getIme()+ " " + admin.getPrezime());
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        lblEmployee.setText(admin.getIme()+ " " + admin.getPrezime());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblEmployee = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        menuBarMain = new javax.swing.JMenuBar();
        menuDelegat = new javax.swing.JMenu();
        menuPredavac = new javax.swing.JMenu();
        menuRezervacija = new javax.swing.JMenu();
        miCreate = new javax.swing.JMenuItem();
        miChange = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME");

        lblEmployee.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblEmployee.setForeground(new java.awt.Color(0, 204, 0));
        lblEmployee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnCancel.setText("izadji");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        menuDelegat.setText(" Delegat");
        menuDelegat.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                menuDelegatMouseDragged(evt);
            }
        });
        menuDelegat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuDelegatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuDelegatMouseEntered(evt);
            }
        });
        menuDelegat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDelegatActionPerformed(evt);
            }
        });
        menuBarMain.add(menuDelegat);

        menuPredavac.setText("Predavac");
        menuPredavac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPredavacMouseClicked(evt);
            }
        });
        menuBarMain.add(menuPredavac);

        menuRezervacija.setText("Rezervacija");

        miCreate.setText("Kreiranje");
        miCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCreateActionPerformed(evt);
            }
        });
        menuRezervacija.add(miCreate);

        miChange.setText("Izmena");
        miChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miChangeActionPerformed(evt);
            }
        });
        menuRezervacija.add(miChange);

        menuBarMain.add(menuRezervacija);

        setJMenuBar(menuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancel)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 364, Short.MAX_VALUE)
                .addComponent(btnCancel)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuDelegatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDelegatActionPerformed

    }//GEN-LAST:event_menuDelegatActionPerformed

    private void menuDelegatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDelegatMouseClicked
        try {
            new FrmDelegat().setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Can not initialize view!\n" + ex.getMessage(), "New Delegat", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_menuDelegatMouseClicked

    private void menuDelegatMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDelegatMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_menuDelegatMouseDragged

    private void menuDelegatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDelegatMouseEntered
    }//GEN-LAST:event_menuDelegatMouseEntered

    private void menuPredavacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPredavacMouseClicked
        try {
            new FrmPredavac().setVisible(true);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Can not initialize view!\n" + ex.getMessage(), "New Predavac", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_menuPredavacMouseClicked

    private void miCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCreateActionPerformed
        new FrmKreirajRezervaciju().setVisible(true);
    }//GEN-LAST:event_miCreateActionPerformed

    private void miChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miChangeActionPerformed
        new FrmIzmeniRezervaciju().setVisible(true);
    }//GEN-LAST:event_miChangeActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        try {
            Controller.getInstance().logout();
            dispose();
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblEmployee;
    private javax.swing.JMenuBar menuBarMain;
    private javax.swing.JMenu menuDelegat;
    private javax.swing.JMenu menuPredavac;
    private javax.swing.JMenu menuRezervacija;
    private javax.swing.JMenuItem miChange;
    private javax.swing.JMenuItem miCreate;
    // End of variables declaration//GEN-END:variables
}
