/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.form;

import domain.Predavac;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import table.model.TableModelPredavac;
import uicontroller.Controller;

/**
 *
 * @author Milan
 */
public class FrmPredavac extends javax.swing.JFrame {

    /**
     * Creates new form FrmPredavac
     */
    //int row=-1;
    List<Predavac> predavaci=new ArrayList<>();
    List<Predavac> predavaciFilter=new ArrayList<>();
    Predavac izabraniPredavac;
    public FrmPredavac() {
        initComponents();
        btnFind.setVisible(false);
        try {
            predavaci=Controller.getInstance().procitajPredavace();
        } catch (Exception ex) {
            Logger.getLogger(FrmPredavac.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        popuniTabelu();
        predavaciFilter=predavaci;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPredavaci = new javax.swing.JTable();
        btnFind = new javax.swing.JButton();
        txtFind = new javax.swing.JTextField();
        btnNew = new javax.swing.JButton();
        btnChange = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnOdustani = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnNadji = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblPredavaci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPredavaci);

        btnFind.setText("nadji");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        btnNew.setText("new");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnChange.setText("change");
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });

        btnDelete.setText("delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnOdustani.setText("izadji");
        btnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdustaniActionPerformed(evt);
            }
        });

        btnReset.setText("reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnNadji.setText("find");
        btnNadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNadjiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNadji)
                .addGap(24, 24, 24)
                .addComponent(btnReset)
                .addGap(33, 33, 33)
                .addComponent(btnFind)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 48, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btnNew)
                .addGap(60, 60, 60)
                .addComponent(btnChange)
                .addGap(71, 71, 71)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOdustani)
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFind)
                    .addComponent(btnReset)
                    .addComponent(btnNadji))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNew)
                    .addComponent(btnChange)
                    .addComponent(btnDelete)
                    .addComponent(btnOdustani))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        
        try {
            new FrmNoviPredavac(this).setVisible(true);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Can not initialize view!\n" + ex.getMessage(), "New Predavac", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        
        int row=tblPredavaci.getSelectedRow();
        predavaci=predavaciFilter;
        if (row!=-1) {
            izabraniPredavac=predavaci.get(row);
            try {
                Controller.getInstance().obrisiPredavac(izabraniPredavac);
                JOptionPane.showMessageDialog(this, "Predavac deleted!\nGenerated ID: [" + izabraniPredavac.getId()+ "]", "Delete Predavac", JOptionPane.INFORMATION_MESSAGE);
                predavaci=Controller.getInstance().procitajPredavace();
                predavaciFilter=predavaci;

                popuniTabelu();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Predavac not deleted!\n" + ex.getMessage(), "Delete Predavac", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Prvo izaberite red tabele", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        predavaci=predavaciFilter;
        int row=tblPredavaci.getSelectedRow();
        if (row!=-1) {
            izabraniPredavac=predavaci.get(row);
            new FrmIzmeniPredavac(this).setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(this, "Prvo izaberite red tabele", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnChangeActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        if (txtFind.getText().isEmpty()) {
            popuniTabelu();
            return;
        }
        String filter=txtFind.getText();
        for (Predavac predavac : predavaci) {
            if (predavac.getIme().equals(filter)) {
                predavaciFilter.add(predavac);
            }
        }
        try {
            TableModelPredavac model=new TableModelPredavac(predavaciFilter);
            tblPredavaci.setModel(model);
        } catch (Exception ex) {
            Logger.getLogger(FrmPredavac.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       predavaciFilter=new ArrayList<>();
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdustaniActionPerformed
        dispose();
    }//GEN-LAST:event_btnOdustaniActionPerformed

    private void btnNadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNadjiActionPerformed
        String filter=txtFind.getText();
        Predavac p=new Predavac();
        if (filter.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Unesite parametar");
            return;
        }
        p.setIme(filter);
        try {
            predavaciFilter=Controller.getInstance().pretraziPredavaca(p);
        } catch (Exception ex) {
            //Logger.getLogger(FrmDelegat.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Predavaci ne postoje");
        }
        predavaci=predavaciFilter;
        popuniTabelu(predavaci);
    }//GEN-LAST:event_btnNadjiActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        try {
            popuniTabelu();
            predavaci=Controller.getInstance().procitajPredavace();
            predavaciFilter=predavaci;
        } catch (Exception ex) {
            Logger.getLogger(FrmDelegat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnNadji;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnOdustani;
    private javax.swing.JButton btnReset;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPredavaci;
    private javax.swing.JTextField txtFind;
    // End of variables declaration//GEN-END:variables

    public void popuniTabelu() {
        
        try {
            predavaci=Controller.getInstance().procitajPredavace();
            TableModelPredavac model=new TableModelPredavac(Controller.getInstance().procitajPredavace());
            tblPredavaci.setModel(model);
            predavaciFilter=predavaci;
        } catch (Exception ex) {
            Logger.getLogger(FrmPredavac.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void popuniTabelu(List<Predavac> predavaci){
        try {
            try {
                TableModelPredavac modelPredavac = new TableModelPredavac(predavaci);
                tblPredavaci.setModel(modelPredavac);
            } catch (Exception ex) {
                System.out.println("Tabela nije uspesno popunjena");
                ex.printStackTrace();
            }

        } catch(Exception e){
            
        }

    }

    public Predavac getIzabraniPredavac() {
        return izabraniPredavac;
    }
}
